// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LittleSwitch: typeof import('./src/components/LittleSwitch.vue')['default']
    Switch: typeof import('@headlessui/vue')['Switch']
  }
}

export { }
